// <auto-generated />
using System;
using Africuisine.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Africuisine.Infrastructure.Migrations.AfricuisineDb
{
    [DbContext(typeof(AfricuisineDbContext))]
    [Migration("20240303153410_AddMeasurements")]
    partial class AddMeasurements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Africuisine.Domain.Entities.Ingredients.IngredientCategory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("LUserUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_IngredientCategories_Name");

                    b.ToTable("IngredientCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4504021e-1429-4009-a6c0-94d1583d5ef3",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3365),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3378),
                            Name = "Proteins",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "920c1721-9b26-4ca4-9b45-b05f23d104aa",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3448),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3448),
                            Name = "Vegetables And Herbs",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "94728605-08cd-4cf7-a75b-2a8190e78f9e",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3457),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3457),
                            Name = "Fruits",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "577bdb1d-dc56-49e7-b69a-390bb7461f90",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3470),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3471),
                            Name = "Grains And Starches",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "6fc4935b-3700-4987-bf95-4e1c421f4cfa",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3541),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3542),
                            Name = "Dairy And Dairy Alternatives",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "1607adb4-cc6a-4ff8-be68-f95f8681eb1f",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3567),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3568),
                            Name = "Condiments And Sauces",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "bedc3f9b-a8df-4960-a0fc-e0fa416ed5e2",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3654),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3655),
                            Name = "Spices And Seasonings",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "9d414470-ba39-469a-884d-0f16d2f7b573",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3666),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3666),
                            Name = "Baking Ingredients",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "ee6180e8-6e69-4284-a93b-14da82cf14b7",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3678),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3678),
                            Name = "Nuts And Seeds",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "21a6b4b2-702e-46b6-b0cf-03d522740e92",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3687),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(3687),
                            Name = "Beverages",
                            SeqNo = 0
                        });
                });

            modelBuilder.Entity("Africuisine.Domain.Entities.Ingredients.Measurement", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LUserUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Measurements_Name");

                    b.ToTable("Measurements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "378e8c51-4863-4c98-a5ec-5168ece07f1b",
                            Abbreviation = "ml",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4613),
                            Description = "Used for liquids, such as water, milk, and oil",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4616),
                            Name = "Milliliter",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "e882efa6-d01d-4f70-b1cb-6c30c5557123",
                            Abbreviation = "l",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4623),
                            Description = "Larger volume measurements, often used for bulk liquids.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4623),
                            Name = "Liters",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "c11269c6-1577-4dc6-8a97-e8cd75abe4f1",
                            Abbreviation = "g",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4627),
                            Description = "Common unit for measuring dry ingredients like flour, sugar, and spices.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4628),
                            Name = "Grams",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "aadbe41b-2767-47cd-8abf-f018fde726d8",
                            Abbreviation = "kg",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4636),
                            Description = "Larger mass measurements, especially for bulk ingredients.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4637),
                            Name = "Kilograms",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "e447a70a-876f-4ec5-9ae2-0820caa3bdb9",
                            Abbreviation = "tsp.",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4640),
                            Description = "Approximately 5 ml.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4641),
                            Name = "Teaspoon",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "5a5be09d-bb2d-4344-8e73-9069aa4e14c4",
                            Abbreviation = "Tbsp",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4647),
                            Description = "Approximately 15 ml.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4647),
                            Name = "Tablespoon",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "6b15dfb3-0052-432f-a997-5d5e5186c6d5",
                            Abbreviation = "250 ml",
                            Creation = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4650),
                            Description = "Used for both liquid and dry ingredients.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 17, 34, 10, 789, DateTimeKind.Local).AddTicks(4651),
                            Name = "Cup",
                            SeqNo = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
