// <auto-generated />
using System;
using Africuisine.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Africuisine.Infrastructure.Migrations.AfricuisineDb
{
    [DbContext(typeof(AfricuisineDbContext))]
    [Migration("20240303142036_AddIngredientCategory")]
    partial class AddIngredientCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Africuisine.Domain.Entities.Ingredients.IngredientCategory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("LUserUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_IngredientCategories_Name");

                    b.ToTable("IngredientCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "494375ab-c69d-413c-aa0c-b0ec45c6c348",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5562),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5571),
                            Name = "Proteins",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "9036acae-e29e-4a2d-80e2-afaa12366ef8",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5637),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5637),
                            Name = "Vegetables And Herbs",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "75367eda-12d2-41d6-b71b-082d75cf9f84",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5644),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5645),
                            Name = "Fruits",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "b5719323-1d85-44c4-b4a8-2707becb568f",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5658),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5659),
                            Name = "Grains And Starches",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "2ca0594b-72ce-43bc-a026-585253c84c63",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5674),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5675),
                            Name = "Dairy And Dairy Alternatives",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "27f4ff9c-df4e-461b-b493-945bb13843d0",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5689),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5690),
                            Name = "Condiments And Sauces",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "f282bc7f-3c63-43f6-b8b6-6b95e8a9f5fe",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5702),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5702),
                            Name = "Spices And Seasonings",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "36a04cd6-244b-4bfe-bc60-a31f844b8949",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5721),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5721),
                            Name = "Baking Ingredients",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "62284ba5-98ea-4c0f-b4b1-eda5334450ef",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5734),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5734),
                            Name = "Nuts And Seeds",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "95014bf6-fa7a-4892-8bf8-d91527df7b34",
                            Creation = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5741),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 3, 3, 16, 20, 36, 21, DateTimeKind.Local).AddTicks(5741),
                            Name = "Beverages",
                            SeqNo = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
