name: Build, Test, and Create Tag on Merge

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal

  create_tag:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' 

      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Increment tag
        id: increment_tag
        run: echo "::set-output name=tag::$(echo ${{ steps.get_tag.outputs.tag }} | awk -F '.' '{print $1"."$2"."$3+1}')"

      - name: Create Tag
        run: |
          echo "Creating tag"
          tag_name="${{ steps.increment_tag.outputs.tag }}" # Get the incremented tag name
          git tag -a $tag_name -m "Version $tag_name"
          git push origin $tag_name
